name: Covid-19 Test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Unit test
        uses: stefanoeb/jest-action@1.0.2
        with:
          test: npm test

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          browser: chrome
          build: npm run build
          start: npm start
          wait-on: http://localhost:4200
